window.nouns = {
  "Page": "die Seite",
  "Foot": "der Fuss",
  "Road": "der Weg",
  "Bake": "backen",
  "Word": "das Wort",
  "Love": "Lieben",
  "Voice": "die Stimme",
  "To try": "Versuchen",
  "Ant": "die Ameise",
  "Banana": "die Banane",
  "Boat": "das Boot",
  "Bus": "der Bus",
  "Roof": "das Dach",
  "Strawberry": "die Erdbeere",
  "Window": "das Fenster",
  "Factory": "die Fabrik",
  "Island": "die Insel",
  "Jacket": "die Jacke",
  "Cook": "der Koch",
  "Cheese": "der Kase",
  "King": "der Kong",
  "Teacher": "der Lehrer",
  "Lamb": "das Lamm",
  "Moon": "der Mond",
  "Mouse": "die Maus",
  "Night": "die Nacht",
  "Side": "der Nebel",
  "Nose": "die Nase",
  "Fruit": "das Obst",
  "Granda": "der Opa",
  "Horse": "das Pferd",
  "Heart": "das Herz",
  "Tooth": "der Zahn",
  "Dog": "der Hund",
  "House": "das Haus",
  "Head": "Der Kopf",
  "Doctor": "der Artz",
  "Profession": "der Beruf",
  "Monkey": "der Affe",
  "Pets": "Das Haustiere",
  "Invitation": "Die Einladung",
  "Father": "der Vater"
}

