window.sentences = {
  "what is your profession? (formal)": "Was sind sie von beruf?",
  "What is your profession? (informal)": "Was bist du von beruf?",
  "She is Architect": "Sie ist Architektin",
  "Are you an Architect? (informal)": "Bist du Architektin?",
  "We are friends": "Wir sind Freunde",
  "They are Germans": "Sie sind Deutsche",
  "How are you? (formal)": "Wie geht es ihnen?",
  "I'm fine thanks": "Mir geht es gut, danke",
  "I'm eating a apple": "Ich esse einen Apfel",
  "I'm drinking a glass of wine": "Ich trink ein Glas Wein",
  "I'm dancing": "Ich tanze",
  "I like dancing very much": "Ich mag tanzen sehr gerne",
  "How old are you?": "Wie alt bist du?",
  "Do you have kids?": "Hast du kinder?",
  "How many children do you have?": "Wie viele kinder hast du?",
  "Is your house big or small?": "Ist dein Haus gross oder klein?",
  "Can you come to the party": "Kannst du auf das Fest kommen?",
  "which languages do you speak?": "Welche Sprachen sprechen Sie?",
  "It's nice to meet you": "Es freut mich sie kennenzulernen",
  "What are you doing?": "Was machen sie?",
}
