window.verbs = {
  "make / do": "machen",
  "what": "Was",
  "be able": "kônnen",
  "Love": "Lieben",
  "To try": "Versuchen",
  "welcome": "begrüßen",
  "to be": "sein",
  "to become": "werden",
  "to have": "haben",
  "to must": "mûssen",
  "to give": "geben",
  "to should": "sollen",
  "to say": "sagen",
  "to want": "wollen",
  "to go": "gehen",
  "to stand": "stehen",
  "to see": "sehen",
  "to find": "finden",
  "to stay": "bleiben",
  "to lie": "liegen",
  "to put": "stellen",
  "to take": "nehmen",
  "to be allowed": "dûrfen",
  "to bring": "bringen",
  "to hold": "halten",
  "to play": "spielen",
  "to be called": "heißen",
  "to know": "wissen",
  "to explain": "erklâren",
  "to belong": "gehôren",
  "to begin": "beginnen",
  "to speak": "sprechen",
  "to do": "tun",
  "to like": "môgen",
  "to win": "gewinnen",
  "to get": "bekommen",
  "to write": "schreiben",
  "to work": "arbeiten",
  "to meet": "treffen",
  "to pay": "bezahlen",
  "to answer": "antworten",
  "to walk": "laufen",
  "to need": "brauchen",
  "to celebrate": "feiren",
  "to drive": "fahren",
  "to search": "suchen",
  "to put": "legen",
  "to believe": "glauben",
  "to seem": "scheinen",
  "to close": "schließen",
  "to lack": "fehlen",
  "to know": "kennen",
  "to ask": "fragen",
  "to live": "wohnen",
}
